/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as ApiSubmitRouteImport } from './routes/api/submit'
import { Route as LocaleTeachRouteImport } from './routes/$locale/teach'
import { Route as LocaleSchoolsRouteImport } from './routes/$locale/schools'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocaleContributeRouteImport } from './routes/$locale/contribute'
import { Route as LocaleContactRouteImport } from './routes/$locale/contact'
import { Route as LocaleAccessibilityRouteImport } from './routes/$locale/accessibility'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'

const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const ApiSubmitRoute = ApiSubmitRouteImport.update({
  id: '/api/submit',
  path: '/api/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTeachRoute = LocaleTeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSchoolsRoute = LocaleSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContributeRoute = LocaleContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAccessibilityRoute = LocaleAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/privacy': typeof PrivacyRoute
  '/schools': typeof SchoolsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/accessibility': typeof LocaleAccessibilityRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/contribute': typeof LocaleContributeRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/schools': typeof LocaleSchoolsRoute
  '/$locale/teach': typeof LocaleTeachRoute
  '/api/submit': typeof ApiSubmitRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/privacy': typeof PrivacyRoute
  '/schools': typeof SchoolsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/accessibility': typeof LocaleAccessibilityRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/contribute': typeof LocaleContributeRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/schools': typeof LocaleSchoolsRoute
  '/$locale/teach': typeof LocaleTeachRoute
  '/api/submit': typeof ApiSubmitRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/privacy': typeof PrivacyRoute
  '/schools': typeof SchoolsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/accessibility': typeof LocaleAccessibilityRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/contribute': typeof LocaleContributeRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/schools': typeof LocaleSchoolsRoute
  '/$locale/teach': typeof LocaleTeachRoute
  '/api/submit': typeof ApiSubmitRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/contribute'
    | '/privacy'
    | '/schools'
    | '/sitemap.xml'
    | '/teach'
    | '/$locale/about'
    | '/$locale/accessibility'
    | '/$locale/contact'
    | '/$locale/contribute'
    | '/$locale/privacy'
    | '/$locale/schools'
    | '/$locale/teach'
    | '/api/submit'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/contribute'
    | '/privacy'
    | '/schools'
    | '/sitemap.xml'
    | '/teach'
    | '/$locale/about'
    | '/$locale/accessibility'
    | '/$locale/contact'
    | '/$locale/contribute'
    | '/$locale/privacy'
    | '/$locale/schools'
    | '/$locale/teach'
    | '/api/submit'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/contribute'
    | '/privacy'
    | '/schools'
    | '/sitemap.xml'
    | '/teach'
    | '/$locale/about'
    | '/$locale/accessibility'
    | '/$locale/contact'
    | '/$locale/contribute'
    | '/$locale/privacy'
    | '/$locale/schools'
    | '/$locale/teach'
    | '/api/submit'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ContactRoute: typeof ContactRoute
  ContributeRoute: typeof ContributeRoute
  PrivacyRoute: typeof PrivacyRoute
  SchoolsRoute: typeof SchoolsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeachRoute: typeof TeachRoute
  ApiSubmitRoute: typeof ApiSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/api/submit': {
      id: '/api/submit'
      path: '/api/submit'
      fullPath: '/api/submit'
      preLoaderRoute: typeof ApiSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/teach': {
      id: '/$locale/teach'
      path: '/teach'
      fullPath: '/$locale/teach'
      preLoaderRoute: typeof LocaleTeachRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/schools': {
      id: '/$locale/schools'
      path: '/schools'
      fullPath: '/$locale/schools'
      preLoaderRoute: typeof LocaleSchoolsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contribute': {
      id: '/$locale/contribute'
      path: '/contribute'
      fullPath: '/$locale/contribute'
      preLoaderRoute: typeof LocaleContributeRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/accessibility': {
      id: '/$locale/accessibility'
      path: '/accessibility'
      fullPath: '/$locale/accessibility'
      preLoaderRoute: typeof LocaleAccessibilityRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleAccessibilityRoute: typeof LocaleAccessibilityRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleContributeRoute: typeof LocaleContributeRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleSchoolsRoute: typeof LocaleSchoolsRoute
  LocaleTeachRoute: typeof LocaleTeachRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleAccessibilityRoute: LocaleAccessibilityRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleContributeRoute: LocaleContributeRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleSchoolsRoute: LocaleSchoolsRoute,
  LocaleTeachRoute: LocaleTeachRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ContactRoute: ContactRoute,
  ContributeRoute: ContributeRoute,
  PrivacyRoute: PrivacyRoute,
  SchoolsRoute: SchoolsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeachRoute: TeachRoute,
  ApiSubmitRoute: ApiSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
